#!/bin/bash


Head() {
  echo -e "\e[1;36m **************************** $1  \e[0m"
  echo -e "\e[1;36m **************************** $1  \e[0m" >>$LOG
}

Stat() {
  if [ "$1" -eq 0 ]; then
    echo -e "\e[1;32m SUCCESS\e[0m"
  else
    echo -e "\e[1;31m FAILURE\e[0m"
    echo -e "\n\e[1;33m You can refer log file fore more information, Log file Path = ${LOG}\e[0m"
    exit 1
  fi
}

Head "updating packages"
apt update -y
Stat $?

Head "installing java"
apt install openjdk-8-jre -y
Stat $?

Head "downloading jenkins key"
wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
Stat $?

Head "updating path location"
sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
Stat $?

Head "again updating packages"
sudo apt-get update -y
Stat $?

Head "installing jenkins"
sudo apt-get install jenkins -y
Stat $?

Head "status of jenkins"
systemctl status jenkins
Stat $?
